package vitor_ag.rir_app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF061734)//0xFF791FEF
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEBDCFF)
val md_theme_light_onPrimaryContainer = Color(0xFF270058)
val md_theme_light_secondary = Color(0xFF665781)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBDCFF)
val md_theme_light_onSecondaryContainer = Color(0xFF221439)
val md_theme_light_tertiary = Color(0xFF93455C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E0)
val md_theme_light_onTertiaryContainer = Color(0xFF3E011A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF323033)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inversePrimary = Color(0xFFD4BBFF)
val md_theme_light_surfaceTint = Color(0xFF791FEF)
val md_theme_light_surfaceTintColor = Color(0xFF791FEF)

val md_theme_dark_primary = Color(0xFFD4BBFF)
val md_theme_dark_onPrimary = Color(0xFF41008B)
val md_theme_dark_primaryContainer = Color(0xFF5D00C2)
val md_theme_dark_onPrimaryContainer = Color(0xFFEBDCFF)
val md_theme_dark_secondary = Color(0xFFD1BEEE)
val md_theme_dark_onSecondary = Color(0xFF372950)
val md_theme_dark_secondaryContainer = Color(0xFF4E4068)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBDCFF)
val md_theme_dark_tertiary = Color(0xFFFFB1C3)
val md_theme_dark_onTertiary = Color(0xFF5A172E)
val md_theme_dark_tertiaryContainer = Color(0xFF762E44)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_outline = Color(0xFF948E99)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF323033)
val md_theme_dark_inversePrimary = Color(0xFF791FEF)
val md_theme_dark_surfaceTint = Color(0xFFD4BBFF)
val md_theme_dark_surfaceTintColor = Color(0xFFD4BBFF)

val seed = Color(0xFF7516EB)
